name: Build & Release APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug


      - name: Find APK
        run: find . -type f -name "*.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "Build ${{ github.run_number }}"
          files: |
            **/build/outputs/apk/debug/*.apk